### ISSUE TITLE
License violation notice of original repository (Artistic 2.0)

### ISSUE THREAD

**Issue by seia-soto** [wonderlandpark/wonderbot#1]
Some codes are violating the Artistic License 2.0 by Perl corporation and applied to [Seia-Soto/Serium](https://github.com/Seia-Soto/Serium) by [myself (Seia-Soto/Serium:commit#0e0943b9)](https://github.com/Seia-Soto/Serium/commit/0e0943b9c5c92b01ca8edcd9264120c762e4801f).

# Violations

Resolve the following violations by accepting [Artistic License 2.0 conditions](https://opensource.org/licenses/Artistic-2.0):

1. https://github.com/wonderlandpark/wonderbot/blob/3f734bcac06ee6a8b2e92ea5baf8a4a13d7833e3/commands/index.js#L1-L25

## Original code

2. https://github.com/Seia-Soto/Serium/blob/9c050078c5f5613cd1546980964a8c84eee98a2a/commands/index.js#L1-L23

## Possible violations

- https://github.com/wonderlandpark/wonderbot/blob/3f734bcac06ee6a8b2e92ea5baf8a4a13d7833e3/index.js#L44-L55

**Comment by wonderlandpark** [comment]
Hello, **Seia-Soto**

I have identified an issue with a license violation.

First of all, I apologize for breaking the license. 
I changed my code to public and missed a lot.

Code used under the Artistic 2.0 license is specified in [README](https://github.com/wonderlandpark/wonderbot#open-source-used-in-project).

I apologize once again for my inconsistency. If I missed something, please create the issue again.

**Comment by wonderlandpark** [comment]
If I missed something, please create a new issue.
