### ISSUE TITLE
[BUG] Security Vulnerability

### ISSUE THREAD

**Issue by zero734kr** [wonderlandpark/wonderbot#105]
**Describe the bug**
There is a security vulnerability in the ``whois`` command that the shard dies after using the command.

**Reproduce**

1. Type the command ``.whois __proto__`` on any discord server that the wonderbot is on.
2. Boom!
3. Check the [website](https://wonderbot.xyz/shards) to see which shard is inactive.
4. See:
![image](https://user-images.githubusercontent.com/51540538/102918612-fb186e00-4465-11eb-83fd-7c6b7fc581da.png)

**Expected behavior**
Send a message alerting you that an error has been thrown or block it before the lookup

**Screenshots**
![image](https://user-images.githubusercontent.com/51540538/102918834-77ab4c80-4466-11eb-88b3-79781d06e289.png)
![image](https://user-images.githubusercontent.com/51540538/102918862-872a9580-4466-11eb-864b-9a387aba5e47.png)

**Additional context**
Sorry about that, I was looking for some security vulnerabilities.

**Comment by wonderlandpark** [comment]
Not a Bug
