### ISSUE TITLE
[제안] 송금 기능

### ISSUE THREAD

**Issue by myungseokang** [wonderlandpark/wonderbot#116]
**기능 요청은 이슈와 관련되어 있습니까?**
사람과 사람 간의 송금 기능을 추가하면 더욱 재밌을 것 같아 제안해봅니다.

**원하는 솔루션을 설명해주세요**
사람과 사람 간의 송금 기능을 추가하면 더욱 재밌을 것 같아 제안해봅니다.

**생각한 대안을 설명해주세요**
```
.송금 @특정인물 금액
```
과 같은 방식으로 사용하면 좋을 것 같아요.

**기타 내용**

없습니다.

**Comment by wonderlandpark** [comment]
구현 예정이 없습니다. 공식 디스코드내 `#자주 물어보는 질문` 채널을 확인해주세요.
