### ISSUE TITLE
Must not use notice command

### ISSUE THREAD

**Issue by wonderlandpark** [wonderlandpark/wonderbot#14]
Notice command is too fast for discord API 
Discord will ban your IP when you use notice command for large bot(Wonder bot has 1800 more servers)

must make this command slower or use webhook for notice.

**Comment by comjun04** [comment]
I recommand using plain message (slower) than sending webhooks.
Because: 
* You can edit messages (API)
* Webhook doesn't have profile info, so some people ~~including me~~ would complain about that.

**Comment by wonderlandpark** [comment]
Webhook author's username and avatar is editable please check the API
Also I will think about for delaying the notice command.

**Comment by wonderlandpark** [comment]
Thanks for your comment
