### ISSUE TITLE
Slot Command Bug (Origin : مشكلة قيادة الفتحة)

### ISSUE THREAD

**Issue by chaemoong** [wonderlandpark/wonderbot#16]
![](https://cdn.discordapp.com/attachments/677722378784079875/679580553280094212/unknown.png)
While using slot command, sometimes return, undefined.

~~أنا أستخدم أمر الفتحة ، وفجأة أحصل على خطأ غير محدد حتى لا أعرف ما الذي سيحدث.~~

**Comment by wonderlandpark** [comment]
This repository only supports, english and Korean. 
Please don't use other language.

**Comment by wonderlandpark** [comment]
Closed for mistake

**Comment by wonderlandpark** [comment]
Just locked because no for edit is not needed
If you have new issue please create new one.

**Comment by wonderlandpark** [comment]
Fixed
