### ISSUE TITLE
README.MD 파일 아이디어 Thanks to 부분 수정해주세요

### ISSUE THREAD

**Issue by chaemoong** [wonderlandpark/wonderbot#19]
저 태그 chaemoong#0001에서 니트로 끝나서 chaemoong#9927로 변경 되었습니다
수정부탁드립니다

**Comment by wonderlandpark** [comment]
확인이 늦었습니다.  https://github.com/wonderlandpark/wonderbot/commit/c862dc54a9f21705fdf55fc3523de7987a9f3c2b 에서 고쳐드렸습니다
