### ISSUE TITLE
I don't think this project is standardjs styled.

### ISSUE THREAD

**Issue by Helloyunho** [wonderlandpark/wonderbot#20]
I was looking up the codes and I found that many codes are against standardjs rules. Here are some of the errors.

https://pastebin.com/raw/GRvVwD6T

Is this project **really** using standardjs code style?

**Comment by wonderlandpark** [comment]
Well for now my text editor is weird and eslint extension is not working. So code style is not correct. I will fix it sorry for that.

**Comment by wonderlandpark** [comment]
(+) Not really Standardjs I should edit README

**Comment by seia-soto** [comment]
This issue should be fixed to improve community accessibility. This requires a full rewrite of the repository codes but should be done. Also, in another word, resolving most of the ESLint and Standard.JS error means we're being more humble to new people of this project and Standard.JS is a developer community-driven project. Again, this issue should be resolved even take a long time.

**Comment by wonderlandpark** [comment]
Thanks for your comment. I will try to resolve this issue. But, for now, I am a little busy. Again, thanks for your comment.

**Comment by wonderlandpark** [comment]
Now, We are not supporting Standard.js. We are using custom eslint rule.
Please Check our [Eslint Config File](https://github.com/wonderlandpark/wonderbot/blob/master/.eslintrc.json)

This issue must be fixed at https://github.com/wonderlandpark/wonderbot/pull/30

For related or other issue, feel free to create new issue
