### ISSUE TITLE
'undefined'error on mask command

### ISSUE THREAD

**Issue by Yoruroong** [wonderlandpark/wonderbot#21]
`.mask 서울특별시 은평구` 
then
![image](https://user-images.githubusercontent.com/33586417/76382312-a2c32480-639b-11ea-97db-95d17cb1f81d.png)

**Comment by wonderlandpark** [comment]
Checked Will fix

**Comment by wonderlandpark** [comment]
Fixed In https://github.com/wonderlandpark/wonderbot/commit/20d6761f27103f9ec0dec87f74749ed2a409e7c3
Thanks for your issue
