### ISSUE TITLE
NEW FEATURE: 로또

### ISSUE THREAD

**Issue by wonderlandpark** [wonderlandpark/wonderbot#26]
로또 시스템

4자리 수 + 보너스 

숫자: 1~30

1등 4자리수 일치
2등 3자리수+보너스 일치
3등 3자리수 일치
4등 2자리수 일치
5등 1자리수 일치

JUST FOR IDEA MEMO XD

**Comment by comjun04** [comment]
~~로또 6/45인가요~~

당첨됐을때 얼마를 주나요?

제 생각에는 (기존 로또처럼)
* 로또를 삼
* 사서 모인 돈 + 저번 로또 후 남은 돈(있다면)을 1, 2등은 %로 쪼개서 줌

이 방식이 좋을 거 같아요

**Comment by wonderlandpark** [comment]
@comjun04 합쳐도 얼마 안될듯하여..

**Comment by wonderlandpark** [comment]
Added At https://github.com/wonderlandpark/wonderbot/commit/fca8c8bb9cfc0ea25740952447eb2bcdfce8f008

Should add Prize
