### ISSUE TITLE
[야바위 버그] 

### ISSUE THREAD

**Issue by rjsdn2494** [wonderlandpark/wonderbot#38]
**버그 설명하기**
제 돈은 110원 밖에 없었고 야바위를 해서 성공을 했습니다. 그런데 분명 채팅에는 배팅금의 2배를 
주겠다고 했지만 실제론 3배를 줬습니다. 

**버그 발생시키기**
야바위를 성공하면 3배를 줍니다.

**예상된 결과**
원래 2배로 줘야 합니다.

**스크린샷**
스크린샷이 있다면 첨부해주세요.

**기타 내용**
원래 3배인지 아니면 2배인데 버그가 생긴건지 알아봐주세요!

**Comment by wonderlandpark** [comment]
CNR

Needs Approve
