### ISSUE TITLE
Slot command cooldown returned text BUG   (ORIGIN : slot 命令语问题)

### ISSUE THREAD

**Issue by chaemoong** [wonderlandpark/wonderbot#7]
![image](https://user-images.githubusercontent.com/49019734/74216237-157ea880-4ce7-11ea-9aca-69d56c852d72.png)
All in Command is missing `seconds` (in korean)

Origin : ~~幾分鐘,幾分鐘,幾秒鐘,或何時,混亂的可能性很大。
請修改一下~~

**Comment by wonderlandpark** [comment]
@chaemoong Thanks for your issue. 
In this repository we only support Korean and English replies. I have understood the issue by image. Thanks for your help!

**Comment by cotwo0139** [comment]
Translated: कुछ मिनटों, कुछ मिनटों, कुछ सेकंडों के लिए या जब, भ्रम की संभावना अधिक होती है।
कृपया संशोधित करें

**Comment by wonderlandpark** [comment]
Feel free to create issue anytime

**Comment by wonderlandpark** [comment]
@cotwo0139 Sorry, I can't understand your language.

**Comment by wonderlandpark** [comment]
Fixed at https://github.com/wonderlandpark/wonderbot/commit/e711ccd48784cead4be08f68a359dccd49a46a8c

**Comment by wonderlandpark** [comment]
Please Reopen issue when you have new issue
