### ISSUE TITLE
[버그] 은행 타임스태프(시간) 오류

### ISSUE THREAD

**Issue by filename24** [wonderlandpark/wonderbot#89]
**버그 설명하기**
버그는 간단합니다 일단 메세지는
```
@!안꿀꿀!, 원더은행을 이용해주셔서 감사합니다.
360원의 빚중에 300원을 상환하셨습니다.

60원의 빚을 1970년 1월 1일 목요일 오후 9:00(51년 전)까지 상환 하셔야합니다
```
나와 있던 1930년 1월1일 목요일이 문제 입니다.

**버그 발생시키기**
버그를 발생시키는 방법입니다.

**예상된 결과**
일반적으로 발생해야하는 결과입니다.
```diff
+ @유저 이름, 원더은행을 이용해주셔서 감사합니다.
360원의 빚중에 300원을 상환하셨습니다.

- 60원의 빚을 2020년 11월 2일 일요일 오후 12:00(1일 후)까지 상환 하셔야합니다.
```
**스크린샷**
없셔

**기타 내용**
참께빵 위에 순쇠고기 패티 두장 특별한 소스 양상추 치즈 피클 양파까지!

**Comment by kijk2869** [comment]
Duplicated with #67

**Comment by wonderlandpark** [comment]
Dupe of #67

**Comment by wonderlandpark** [comment]
다음부터는 이슈에서 장난식의 메세지는 포함하지 말아주세요.
